### ISSUE TITLE
How to configure the production environemnt

### ISSUE THREAD

**Issue by ramshankar1988** [openfun/openedx-docker#206]
I need your help in making the environment for production ready.
How do i configure the MYSQL and mongoDB environemnt for production version?
I am using RDS-Mysql and MongoDB Atlas for the prodution work load.

**Comment by sampaccoud** [comment]
For MongoDB, the best in production is to declare all nodes in the cluster to pymongo via a **replicaset**. In `openedx-docker`, you should [set these environment variables](https://github.com/openfun/openedx-docker/blob/master/releases/hawthorn/1/oee/config/lms/docker_run_production.py#L756) (you can also configure them via a yaml file). For example, if you have 3 nodes in your cluster with IP addresses `10.10.0.1`, `10.10.0.2` and `10.10.0.3`:
```yaml
MONGODB_HOST="10.10.0.1,10.10.0.2,10.10.0.3"
MONGODB_REPLICASET="edx"
MONGODB_READ_PREFERENCE="PRIMARY_PREFERRED"
```

For Mysql, you should set [these environment variables](https://github.com/openfun/openedx-docker/blob/master/releases/hawthorn/1/oee/config/lms/docker_run_production.py#L723) (you can also configure them via a yaml file). For example:
```yaml
DATABASE_HOST="yourDBHost"
DATABASE_NAME="yourDBName"
DATABASE_USER="yourDBUser"
DATABASE_PASSWORD="YourDBPassword"
```

I hope this is helpful and answers your question?

**Comment by ramshankar1988** [comment]
Thanks. 
And after changing the values of mongo and MySQL, I need to use make build command right?
This will create an docker image in my local machine and need to push to dockerhub, is it correct?

**Comment by ramshankar1988** [comment]
Getting below mentioned error while executing "make build" command.
ERROR: Service 'lms' failed to build: The command '/bin/sh -c curl -sLo edxapp.tgz https://github.com/edx/edx-platform/archive/$EDX_RELEASE_REF.tar.gz &&     tar xzf edxapp.tgz' returned a non-zero code: 6
Makefile:138: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by sampaccoud** [comment]
@ramshankar1988 no you don't need to rebuild the image. You can run on the image we provide in dockerhub https://hub.docker.com/r/fundocker/edxapp. 
You need to set the environment variables while running these images. How this is done depends on the service you use to run Docker images.

**Comment by ramshankar1988** [comment]
Sure. Is there any documentation or steps available to host the production build? Like a checklist which helps a lot.

**Comment by sampaccoud** [comment]
Unfortunately we don't have this yet.

What I can say is that it can be deployed as any 12-factor auth application. Configuration can be done via environment variables. The available configurable settings are all those wrapped in `config(...)` in [this file](https://github.com/openfun/openedx-docker/blob/master/releases/master/bare/config/cms/docker_run_production.py) for the cms and [this file](https://github.com/openfun/openedx-docker/blob/master/releases/master/bare/config/lms/docker_run_production.py) for the lms. If you already know Open edX, it shouldn't be too hard. Otherwise, you should start with the default values with provide and see what you get. I don't know of any documentation for all these settings... 

If you think this is too complex, I can recommend another project, that tries to make Open edX installable in "one-click". It is quite popular as a first approach to the beast: https://docs.tutor.overhang.io/

**Comment by ramshankar1988** [comment]
Sure, will follow the guide lines to change env variables.
